FROM nvidia/cuda:12.6.1-devel-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    cmake \
    gfortran \
    git \
    && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
