FROM rocm/dev-ubuntu-22.04:6.2-complete

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    cmake \
    gfortran \
    git \
    && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

ENV PATH=/opt/rocm/bin:$PATH
